services:
  db:
      image: mysql/mysql-server:5.7
      environment:
        MYSQL_ROOT_PASSWORD: macpython
        MYSQL_PASSWORD: macpython
        MYSQL_USER: test
        TZ: Asia/Shanghai
      networks:
        - default
#      ports:
#        - 3306:3306
      command:
        --default-authentication-plugin=mysql_native_password 
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci

#        grant all privileges on *.* to root@'%' identified by 'macpython' with grant option
#        flush privileges

  redis:
      image: redis
      networks:
        - default

  cas:
    build: ../src/cas
    restart: on-failure
    environment:
      host: redis
      port: 6379
      expire: 720000
      attack: 10
      salt: bigdata@2021
      flask_ip: 0.0.0.0
      flask_port: 20000
    depends_on:
      - redis
    command: python3 service.py
    networks:
      - default

  flask:
    build: ../src/template
    restart: on-failure
    environment:
      host: db
      port: 3306
      username: root
      password: macpython
      db: template
      charset: utf8
#      charset: utf8mb4
      pool_size: 200
      max_overflow: 300
      bulk: 1000
      initialize: 'True'
      flask_ip: 0.0.0.0
      flask_port: 6000
    depends_on:
      - cas
      - db
    networks:
      - default
    command: python3 service.py
    ports:
      - 6000:6000

networks:
  default:
      driver: bridge

