// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: env_manager.proto

package envmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{0}
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type EnvConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapName    string `protobuf:"bytes,1,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	NumThreads int64  `protobuf:"varint,2,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
}

func (x *EnvConfig) Reset() {
	*x = EnvConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvConfig) ProtoMessage() {}

func (x *EnvConfig) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvConfig.ProtoReflect.Descriptor instead.
func (*EnvConfig) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{2}
}

func (x *EnvConfig) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

func (x *EnvConfig) GetNumThreads() int64 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

type EnvSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseId  int64        `protobuf:"varint,1,opt,name=base_id,json=baseId,proto3" json:"base_id,omitempty"`
	Configs []*EnvConfig `protobuf:"bytes,2,rep,name=configs,proto3" json:"configs,omitempty"`
}

func (x *EnvSchema) Reset() {
	*x = EnvSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvSchema) ProtoMessage() {}

func (x *EnvSchema) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvSchema.ProtoReflect.Descriptor instead.
func (*EnvSchema) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{3}
}

func (x *EnvSchema) GetBaseId() int64 {
	if x != nil {
		return x.BaseId
	}
	return 0
}

func (x *EnvSchema) GetConfigs() []*EnvConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type CreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EndId  int64 `protobuf:"varint,1,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	Status int64 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReply) GetEndId() int64 {
	if x != nil {
		return x.EndId
	}
	return 0
}

func (x *CreateReply) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Array struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nbytes  int64   `protobuf:"varint,1,opt,name=nbytes,proto3" json:"nbytes,omitempty"`
	Dtype   int64   `protobuf:"varint,2,opt,name=dtype,proto3" json:"dtype,omitempty"`
	Shapes  []int64 `protobuf:"varint,3,rep,packed,name=shapes,proto3" json:"shapes,omitempty"`
	Ndarray []byte  `protobuf:"bytes,4,opt,name=ndarray,proto3" json:"ndarray,omitempty"`
}

func (x *Array) Reset() {
	*x = Array{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{5}
}

func (x *Array) GetNbytes() int64 {
	if x != nil {
		return x.Nbytes
	}
	return 0
}

func (x *Array) GetDtype() int64 {
	if x != nil {
		return x.Dtype
	}
	return 0
}

func (x *Array) GetShapes() []int64 {
	if x != nil {
		return x.Shapes
	}
	return nil
}

func (x *Array) GetNdarray() []byte {
	if x != nil {
		return x.Ndarray
	}
	return nil
}

type EnvArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnvId     int64    `protobuf:"varint,1,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	TimeSteps int64    `protobuf:"varint,2,opt,name=time_steps,json=timeSteps,proto3" json:"time_steps,omitempty"`
	Type      string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Done      bool     `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty"`
	Array     []*Array `protobuf:"bytes,5,rep,name=array,proto3" json:"array,omitempty"`
}

func (x *EnvArray) Reset() {
	*x = EnvArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvArray) ProtoMessage() {}

func (x *EnvArray) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvArray.ProtoReflect.Descriptor instead.
func (*EnvArray) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{6}
}

func (x *EnvArray) GetEnvId() int64 {
	if x != nil {
		return x.EnvId
	}
	return 0
}

func (x *EnvArray) GetTimeSteps() int64 {
	if x != nil {
		return x.TimeSteps
	}
	return 0
}

func (x *EnvArray) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EnvArray) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *EnvArray) GetArray() []*Array {
	if x != nil {
		return x.Array
	}
	return nil
}

type AgentDecision struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action *EnvArray `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *AgentDecision) Reset() {
	*x = AgentDecision{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDecision) ProtoMessage() {}

func (x *AgentDecision) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDecision.ProtoReflect.Descriptor instead.
func (*AgentDecision) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{7}
}

func (x *AgentDecision) GetAction() *EnvArray {
	if x != nil {
		return x.Action
	}
	return nil
}

type EnvReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column *EnvArray `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *EnvReply) Reset() {
	*x = EnvReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnvReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvReply) ProtoMessage() {}

func (x *EnvReply) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvReply.ProtoReflect.Descriptor instead.
func (*EnvReply) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{8}
}

func (x *EnvReply) GetColumn() *EnvArray {
	if x != nil {
		return x.Column
	}
	return nil
}

type ResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request *EnvArray `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{9}
}

func (x *ResetRequest) GetRequest() *EnvArray {
	if x != nil {
		return x.Request
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloseIds []int64 `protobuf:"varint,1,rep,packed,name=close_ids,json=closeIds,proto3" json:"close_ids,omitempty"`
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{10}
}

func (x *CloseRequest) GetCloseIds() []int64 {
	if x != nil {
		return x.CloseIds
	}
	return nil
}

type CloseReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClosedIds []int64 `protobuf:"varint,1,rep,packed,name=closed_ids,json=closedIds,proto3" json:"closed_ids,omitempty"`
	Status    bool    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CloseReply) Reset() {
	*x = CloseReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseReply) ProtoMessage() {}

func (x *CloseReply) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseReply.ProtoReflect.Descriptor instead.
func (*CloseReply) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{11}
}

func (x *CloseReply) GetClosedIds() []int64 {
	if x != nil {
		return x.ClosedIds
	}
	return nil
}

func (x *CloseReply) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type BlockDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxBlockSize int64 `protobuf:"varint,1,opt,name=max_block_size,json=maxBlockSize,proto3" json:"max_block_size,omitempty"`
	MinBlockSize int64 `protobuf:"varint,2,opt,name=min_block_size,json=minBlockSize,proto3" json:"min_block_size,omitempty"`
	Mode         int64 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
}

func (x *BlockDescription) Reset() {
	*x = BlockDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockDescription) ProtoMessage() {}

func (x *BlockDescription) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockDescription.ProtoReflect.Descriptor instead.
func (*BlockDescription) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{12}
}

func (x *BlockDescription) GetMaxBlockSize() int64 {
	if x != nil {
		return x.MaxBlockSize
	}
	return 0
}

func (x *BlockDescription) GetMinBlockSize() int64 {
	if x != nil {
		return x.MinBlockSize
	}
	return 0
}

func (x *BlockDescription) GetMode() int64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type BlockReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready   bool        `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	End     bool        `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Columns []*EnvArray `protobuf:"bytes,3,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *BlockReply) Reset() {
	*x = BlockReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_env_manager_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReply) ProtoMessage() {}

func (x *BlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_env_manager_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReply.ProtoReflect.Descriptor instead.
func (*BlockReply) Descriptor() ([]byte, []int) {
	return file_env_manager_proto_rawDescGZIP(), []int{13}
}

func (x *BlockReply) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BlockReply) GetEnd() bool {
	if x != nil {
		return x.End
	}
	return false
}

func (x *BlockReply) GetColumns() []*EnvArray {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_env_manager_proto protoreflect.FileDescriptor

var file_env_manager_proto_rawDesc = []byte{
	0x0a, 0x11, 0x65, 0x6e, 0x76, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x22, 0x09, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1f, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x47, 0x0a, 0x09, 0x45, 0x6e, 0x76, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x61, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x61, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x75, 0x6d, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x73, 0x22, 0x52, 0x0a, 0x09, 0x45, 0x6e, 0x76, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x17,
	0x0a, 0x07, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x62, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x3c, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x67, 0x0a, 0x05, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68,
	0x61, 0x70, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x73, 0x68, 0x61, 0x70,
	0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x64, 0x61, 0x72, 0x72, 0x61, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x6e, 0x64, 0x61, 0x72, 0x72, 0x61, 0x79, 0x22, 0x8e, 0x01, 0x0a,
	0x08, 0x45, 0x6e, 0x76, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x76,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x6e, 0x76, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x12, 0x24, 0x0a, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x05, 0x61, 0x72, 0x72, 0x61, 0x79, 0x22, 0x3a, 0x0a,
	0x0d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x35, 0x0a, 0x08, 0x45, 0x6e, 0x76,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x45, 0x6e, 0x76, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x22, 0x3b, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2b, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2b, 0x0a,
	0x0c, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x49, 0x64, 0x73, 0x22, 0x43, 0x0a, 0x0a, 0x43, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x64, 0x49, 0x64, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22,
	0x72, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x61, 0x78,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x69, 0x6e,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6d,
	0x6f, 0x64, 0x65, 0x22, 0x61, 0x0a, 0x0a, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x07, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x32, 0x97, 0x02, 0x0a, 0x0c, 0x45, 0x6e, 0x76, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x52, 0x50, 0x43, 0x12, 0x29, 0x0a, 0x05, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x12, 0x10, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x35, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x76, 0x12,
	0x12, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x38, 0x0a, 0x08, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x45, 0x6e, 0x76, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x74, 0x65, 0x70, 0x45, 0x6e, 0x76, 0x12, 0x16,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x44, 0x65,
	0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x11, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x2e, 0x45, 0x6e, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x30, 0x01, 0x12, 0x31, 0x0a,
	0x08, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45, 0x6e, 0x76, 0x12, 0x10, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0x79, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x12, 0x39,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x13, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x04, 0x53, 0x74, 0x65,
	0x70, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x28, 0x01, 0x42, 0x37, 0x5a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x65, 0x67, 0x65, 0x57, 0x6f,
	0x6e, 0x67, 0x2f, 0x45, 0x6e, 0x76, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2d, 0x47, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6e, 0x76, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_env_manager_proto_rawDescOnce sync.Once
	file_env_manager_proto_rawDescData = file_env_manager_proto_rawDesc
)

func file_env_manager_proto_rawDescGZIP() []byte {
	file_env_manager_proto_rawDescOnce.Do(func() {
		file_env_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_env_manager_proto_rawDescData)
	})
	return file_env_manager_proto_rawDescData
}

var file_env_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_env_manager_proto_goTypes = []interface{}{
	(*Request)(nil),          // 0: manager.Request
	(*Reply)(nil),            // 1: manager.Reply
	(*EnvConfig)(nil),        // 2: manager.EnvConfig
	(*EnvSchema)(nil),        // 3: manager.EnvSchema
	(*CreateReply)(nil),      // 4: manager.CreateReply
	(*Array)(nil),            // 5: manager.Array
	(*EnvArray)(nil),         // 6: manager.EnvArray
	(*AgentDecision)(nil),    // 7: manager.AgentDecision
	(*EnvReply)(nil),         // 8: manager.EnvReply
	(*ResetRequest)(nil),     // 9: manager.ResetRequest
	(*CloseRequest)(nil),     // 10: manager.CloseRequest
	(*CloseReply)(nil),       // 11: manager.CloseReply
	(*BlockDescription)(nil), // 12: manager.BlockDescription
	(*BlockReply)(nil),       // 13: manager.BlockReply
}
var file_env_manager_proto_depIdxs = []int32{
	2,  // 0: manager.EnvSchema.configs:type_name -> manager.EnvConfig
	5,  // 1: manager.EnvArray.array:type_name -> manager.Array
	6,  // 2: manager.AgentDecision.action:type_name -> manager.EnvArray
	6,  // 3: manager.EnvReply.column:type_name -> manager.EnvArray
	6,  // 4: manager.ResetRequest.request:type_name -> manager.EnvArray
	6,  // 5: manager.BlockReply.columns:type_name -> manager.EnvArray
	0,  // 6: manager.EnvManageRPC.Check:input_type -> manager.Request
	3,  // 7: manager.EnvManageRPC.CreateEnv:input_type -> manager.EnvSchema
	9,  // 8: manager.EnvManageRPC.ResetEnv:input_type -> manager.ResetRequest
	7,  // 9: manager.EnvManageRPC.StepEnv:input_type -> manager.AgentDecision
	0,  // 10: manager.EnvManageRPC.CloseEnv:input_type -> manager.Request
	12, // 11: manager.DataBuffer.Request:input_type -> manager.BlockDescription
	7,  // 12: manager.DataBuffer.Step:input_type -> manager.AgentDecision
	1,  // 13: manager.EnvManageRPC.Check:output_type -> manager.Reply
	4,  // 14: manager.EnvManageRPC.CreateEnv:output_type -> manager.CreateReply
	8,  // 15: manager.EnvManageRPC.ResetEnv:output_type -> manager.EnvReply
	8,  // 16: manager.EnvManageRPC.StepEnv:output_type -> manager.EnvReply
	11, // 17: manager.EnvManageRPC.CloseEnv:output_type -> manager.CloseReply
	13, // 18: manager.DataBuffer.Request:output_type -> manager.BlockReply
	1,  // 19: manager.DataBuffer.Step:output_type -> manager.Reply
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_env_manager_proto_init() }
func file_env_manager_proto_init() {
	if File_env_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_env_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Array); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentDecision); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnvReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_env_manager_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_env_manager_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_env_manager_proto_goTypes,
		DependencyIndexes: file_env_manager_proto_depIdxs,
		MessageInfos:      file_env_manager_proto_msgTypes,
	}.Build()
	File_env_manager_proto = out.File
	file_env_manager_proto_rawDesc = nil
	file_env_manager_proto_goTypes = nil
	file_env_manager_proto_depIdxs = nil
}
